disabled_rules: # rule identifiers to exclude from running
- colon
- comma
- force_cast
- type_name
- line_length
- identifier_name
- trailing_whitespace
- file_header
opt_in_rules:
- empty_count
- file_header
- explicit_init
- closure_spacing
- overridden_super_call
- redundant_nil_coalescing
- private_outlet
- nimble_operator
- attributes
- operator_usage_whitespace
- closure_end_indentation
- first_where
- sorted_imports
- object_literal
- number_separator
- prohibited_super_call
- fatal_error_message
